image: node:latest
cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - yarn
    - cp .env-test .env
  script:
    - echo "Start building App"
    - yarn build
    - echo "Build successfully!"
  artifacts:
    paths:
      - build
  only:
    - master

deploy:
  stage: deploy
  needs:
    - job: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq lftp
  script:
    - ls
    - cd build
    - lftp ftp://admin_hr:28G3056m@hr.safacaki.net -e "set ftp:ssl-allow false; mirror -eRnv ./ public_html/; exit;"
  only:
    - master
  when: on_success
